# Generated by Django 2.2.12 on 2022-06-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220615_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('food_name', models.CharField(max_length=200, verbose_name='Food Name')),
                ('food_description', models.TextField(blank=True, null=True)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('food_category', models.CharField(max_length=100, verbose_name='category')),
                ('is_enabled', models.BooleanField()),
                ('is_deleted', models.BooleanField()),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
