# Generated by Django 2.2.12 on 2022-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
